[package]
name = "myapp-common"
version = "0.1.0"
edition = "2021"

[features]
default = []
user = ["aya"]

[dependencies]
aya = { version = "0.12", optional = true, path = "../../aya/aya" }
network-types = "0.0.6"
log = "0.4.22"

[lib]
path = "src/lib.rs"
