[package]
name = "myapp"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aya = "0.12"
aya-log = "0.2"
env_logger = "0.11.5"
libc = "0.2.155"

[[bin]]
name = "myapp"
path = "src/main.rs"
